language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t cosminchiriac/docker-react -f Dockerfile.dev .

script:
  - docker -e CI=true cosminchiriac/docker-react npm run test